### ISSUE TITLE
Relax dependency on requests-oauthlib

### ISSUE THREAD

**Issue by adamhowardprice** [Asana/python-asana#101]
In your [requirements.txt](https://github.com/Asana/python-asana/blob/master/requirements.txt#L2) you depend on `requests_oauthlib>=0.8.0<2.0`, but in your [setup.py](https://github.com/Asana/python-asana/blob/master/setup.py#L30), it says:
```
install_requires=[
        'requests >= 2.20.0, == 2.*',
        'requests_oauthlib >= 0.8.0, == 0.8.*',
        'six >= 1.10, == 1.*'
    ],
```
Why is there a difference between the two? This is forcing our project to use `0.8.0`, which makes using this library impossible, because another dependency requires `requests-oauthlib>=1.0.0`.

**Comment by w8s** [comment]
I just ran into this issue. It is breaking a build for me.

**Comment by rossgrambo** [comment]
Thank you @w8s for the PR. I merged it in. If either of you can't use the repo version and need a new release asap, let me know. Otherwise I'll get to this in early january.

**Comment by w8s** [comment]
Thanks so much for the quick response and resolution!

**Comment by adamhowardprice** [comment]
Thanks @rossgrambo ! Will you be deploying this release to PyPi soon?

**Comment by w8s** [comment]
Echoing @adamhowardprice: What is the ETA on releasing `0.9.2` to PyPi? Appreciate the prompt patching, @rossgrambo. 🙌

**Comment by rossgrambo** [comment]
Build failed without bumping the version. Went ahead and bumped and redeployed. I see it on PyPi now! Let me know if either you have any have issues!

**Comment by w8s** [comment]
That fixed my issue. Thanks!
