### ISSUE TITLE
Accessing images associated with tasks via the Python API

### ISSUE THREAD

**Issue by jamois** [Asana/python-asana#109]
I would like to access the images associated with tasks using the API but it does not appear to be documented.  Given you are providing the user's profile image (which is way less important than the images associated with project tasks), I am hoping there is way to also access task images.  Thx

**Comment by jjschnei** [comment]
@jamois images on tasks are called attachments in the Asana API. You can certainly read and write attachments on tasks. Here's how to do so in the

**Comment by jamois** [comment]
Awesome.  I kept looking for "image" or "picture" in the API doc.  Thanks for the help!
