### ISSUE TITLE
Getting memberships through get_task with opt_fields does not work

### ISSUE THREAD

**Issue by gerardsyd** [Asana/python-asana#114]
Hi - I am trying something like this:

`print(client.tasks.get_task('1177562507257193', {
      'opt_fields': "memberships, custom_fields, tags"}))`

I get custom_fields and tags but memberships show up as an empty dictionary inside of an empty list. If I do not use opt_fields, I get values under memberships which shows me the projects and sections the specific task is in.

**Comment by rossgrambo** [comment]
Hey @gerardsyd ,

This is a common confusion point with memberships. You'll need to use "memberships.project" & "memberships.section" if you want the data to show up. Let me know if you still have any issues!
