### ISSUE TITLE
Team Memberships : 'Client' object has no attribute 'team_memberships'

### ISSUE THREAD

**Issue by talhakalim** [Asana/python-asana#119]
It seems that the team memberships piece of the API is not working in Pythons
team_members = client.team_memberships.get_team_memberships_for_team(this_team['gid'], {}, opt_pretty=True)
AttributeError: 'Client' object has no attribute 'team_memberships'

**Comment by rossgrambo** [comment]
Can you run:

```
import asana
print("ASANA VERSION:" + asana.__version__)
```

To confirm what version you're on?

**Comment by talhakalim** [comment]
I am on ASANA VERSION: 0.10.0

I have worked around by manually adding the team_memberships.py and creating a stub class in there pointing to gen/team_memberships.py. Which got things rolling.

**Comment by rossgrambo** [comment]
Thank you @talhakalim !

This should be resolved in [0.10.1](https://github.com/Asana/python-asana/releases/tag/v0.10.1)
