### ISSUE TITLE
Official Documentation Needs Updated

### ISSUE THREAD

**Issue by drkinder** [Asana/python-asana#121]
At python-asana/asana/resources/attachments.py method **create_on_task** is referred to as **create_attachment_for_task** in the official documentation at https://developers.asana.com/docs/upload-an-attachment

**Comment by rossgrambo** [comment]
Thanks for pointing this out! We ended up adding "create_attachment_for_task" as an alias of create_on_task, as we're trying to move to a more consistent naming convention of verb_object_for_container. It should be included in 0.10.3
