### ISSUE TITLE
Is asana pypi package officially maintained?

### ISSUE THREAD

**Issue by romansergey** [Asana/python-asana#129]
Hi team,

I noticed that Pypi's `asana` package is a few versions behind, missing description and the listed maintainers don't seem to be participating in the project maintenance anymore.

https://pypi.org/project/asana/

Is that an officially supported package source or should I pull it straight out of the github repo?

**Comment by wdoekes** [comment]
Looks like https://pypi.org/project/asana/ has the latest 1.0, right? Does that mean this issue is fixed?

**Comment by jv-asana** [comment]
Hi @romansergey and @wdoekes,

We are currently working on ways to better maintain our client libraries and are in the process of making updates to the libraries to make it easier for us to maintain as well as keep up to date with the API.

Feel free to add your feedback in this forum post: https://forum.asana.com/t/how-should-we-improve-our-client-libraries/211347/6
