### ISSUE TITLE
Go SDK + CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [Asana/python-asana#163]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in an Asana plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Asana data to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by jv-asana** [comment]
Hi @yevgenypats, we do not have the bandwidth to maintain this plugin. However, you are welcome to [submit your plugin](https://developers.asana.com/docs/submit-your-app) to us so we can list it in our app directory for our users to see.
