### ISSUE TITLE
External string IDs are not supported on task objects

### ISSUE THREAD

**Issue by noonhub** [Asana/python-asana#17]
tasks.find_by_id() only takes a numeric ID and therefore does not support string external IDs. Consider supporting string IDs or a separate method to look up external IDs.

https://github.com/Asana/python-asana/blob/master/asana/resources/gen/tasks.py#L53

**Comment by lorddaedra** [comment]
:+1:

**Comment by noonhub** [comment]
This should be fixed now per https://github.com/Asana/python-asana/commit/64840ce26008b73fa80249c3d4837611fbf361d8 where we accept all IDs as strings
