### ISSUE TITLE
Adding tags to tasks are not working well

### ISSUE THREAD

**Issue by kutysam** [Asana/python-asana#190]
Tag example is wrong.
Correct: body = {"data": {"tag": "TAG_GUID"}}

This should be the correct one instead of 
Wrong: body = {"data": {"param1": "value1", "param2": "value2",}} # dict | The tag to add to the task.
https://github.com/Asana/python-asana/blob/v5.0.3/docs/TasksApi.md#add_tag_for_task

Do try it out and see. 

```
for normal api, it should be like this
https://app.asana.com/api/1.0/tasks/task_GUID/addTag
{
  "data": {
    "tag": tag_GUID
  }
}

**Comment by kutysam** [comment]
Yup understood. I just found it odd to specify more params in the example when the only param that is being accepted is "tag". But I understand you guys are doing a WIP for it.

On a side note: is there any repo that i can create an issue for the documentation?
They specified body params -> tag -> string. I would like to create a modification of "The tag to add to the task" to "The tag's GUID to add to the task")

**Comment by jv-asana** [comment]
Yes. Feedback for the Asana developer documentation text changes can be provided by clicking on the **"Send feedback"** button which links to: https://form-beta.asana.com/?k=C4sELCq6hAUsoWEY0kJwAA&d=15793206719

<img width="2552" alt="send_feedback_button" src="https://github.com/Asana/python-asana/assets/99784540/db393210-29fd-402e-aa94-ba4ebeb26651">

For a bit of context, the [Asana API Reference in the Asana Developer Documentation](https://developers.asana.com/reference/rest-api-reference) is generated from [Asana's public OpenAPI Spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml) located in the [Asana/openapi](https://github.com/Asana/openapi) repo.

If you search through the [Asana public OpenAPI Spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml) for **_"The tag to add to the task"_** you can see how this description is being pulled into the description for `tag` request body params for the [Add a tag to a task](https://developers.asana.com/reference/addtagfortask) endpoint
