### ISSUE TITLE
Too restrictive requirements

### ISSUE THREAD

**Issue by utapyngo** [Asana/python-asana#60]
We use `asana==0.6.5` and want to upgrade requests to the latest version `requests==2.18.4`.
However, in `setup.py` you require `requests==2.14`:

https://github.com/Asana/python-asana/blob/7475f9419619da628b7122271e36a13196068ecb/setup.py#L29

Will asana client break with `requests==2.18`? If not, please make requirements less restrictive.
Something like `>=2.14.2, <3.0a0`.

**Comment by theaeolianmachine** [comment]
Hi @utapyngo,

This one definitely slipped under our radar, and we're sorry about it. I definitely agree, and after doing some tests we'll change it to:

`requests >= 2.14, == 2.*`

Will keep you posted.

**Comment by theaeolianmachine** [comment]
Opened #61.

**Comment by utapyngo** [comment]
Will you please release this fix to PyPI?

**Comment by theaeolianmachine** [comment]
Yeah for sure, just need to cut a minor release which I'll hopefully get to today/tomorrow.

**Comment by theaeolianmachine** [comment]
This has been released on PyPi as 0.6.7.
