### ISSUE TITLE
error: [Errno 2] No such file or directory: 'LICENSE'

### ISSUE THREAD

**Issue by solarmist** [Asana/python-asana#80]
I'm seeing this error:

  Error installing package using `[/Users/me/repos/reviewboard_/build/li-reviewboard/venv/bin/python, /Users/me/repos/reviewboard_/build/li-reviewboard/venv/bin/pip, wheel, --disable-pip-version-check, --wheel-dir, /Users/me/repos/reviewboard_/build/li-reviewboard/wheel-cache, --no-deps, /Users/me/.gradle/caches/modules-2/files-2.1/pypi/asana/0.8.0/2edf9f431135d6475c39ec3dc02b8cf25e59d3d4/asana-0.8.0.tar.gz]`
  Processing /Users/me/.gradle/caches/modules-2/files-2.1/pypi/asana/0.8.0/2edf9f431135d6475c39ec3dc02b8cf25e59d3d4/asana-0.8.0.tar.gz
  Building wheels for collected packages: asana
  Running setup.py bdist_wheel for asana: started
  Running setup.py bdist_wheel for asana: finished with status 'error'
  Complete output from command /Users/me/repos/reviewboard_/build/li-reviewboard/venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/12/5hmv84v57qxd1949p9g_8fsm000j7z/T/pip-QWvvf5-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/12/5hmv84v57qxd1949p9g_8fsm000j7z/T/tmpAulsv7pip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/asana
  copying asana/page_iterator.py -> build/lib/asana
  copying asana/error.py -> build/lib/asana
  copying asana/client.py -> build/lib/asana
  copying asana/session.py -> build/lib/asana
  copying asana/__init__.py -> build/lib/asana
  creating build/lib/asana/resources
  copying asana/resources/tags.py -> build/lib/asana/resources
  copying asana/resources/tasks.py -> build/lib/asana/resources
  copying asana/resources/sections.py -> build/lib/asana/resources
  copying asana/resources/organization_exports.py -> build/lib/asana/resources
  copying asana/resources/users.py -> build/lib/asana/resources
  copying asana/resources/events.py -> build/lib/asana/resources
  copying asana/resources/teams.py -> build/lib/asana/resources
  copying asana/resources/stories.py -> build/lib/asana/resources
  copying asana/resources/__init__.py -> build/lib/asana/resources
  copying asana/resources/attachments.py -> build/lib/asana/resources
  copying asana/resources/project_statuses.py -> build/lib/asana/resources
  copying asana/resources/custom_field_settings.py -> build/lib/asana/resources
  copying asana/resources/custom_fields.py -> build/lib/asana/resources
  copying asana/resources/webhooks.py -> build/lib/asana/resources
  copying asana/resources/projects.py -> build/lib/asana/resources
  copying asana/resources/project_memberships.py -> build/lib/asana/resources
  copying asana/resources/workspaces.py -> build/lib/asana/resources
  creating build/lib/asana/resources/gen
  copying asana/resources/gen/tags.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/tasks.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/sections.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/organization_exports.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/users.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/events.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/teams.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/stories.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/__init__.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/attachments.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/project_statuses.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/custom_field_settings.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/custom_fields.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/webhooks.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/projects.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/project_memberships.py -> build/lib/asana/resources/gen
  copying asana/resources/gen/workspaces.py -> build/lib/asana/resources/gen
  installing to build/bdist.macosx-10.10-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-10.10-x86_64
  creating build/bdist.macosx-10.10-x86_64/wheel
  creating build/bdist.macosx-10.10-x86_64/wheel/asana
  copying build/lib/asana/page_iterator.py -> build/bdist.macosx-10.10-x86_64/wheel/asana
  copying build/lib/asana/error.py -> build/bdist.macosx-10.10-x86_64/wheel/asana
  copying build/lib/asana/client.py -> build/bdist.macosx-10.10-x86_64/wheel/asana
  creating build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/tags.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/tasks.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/sections.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/organization_exports.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/users.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/events.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/teams.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/stories.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/__init__.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  creating build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/tags.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/tasks.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/sections.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/organization_exports.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/users.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/events.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/teams.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/stories.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/__init__.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/attachments.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/project_statuses.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/custom_field_settings.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/custom_fields.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/webhooks.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/projects.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/project_memberships.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/gen/workspaces.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources/gen
  copying build/lib/asana/resources/attachments.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/project_statuses.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/custom_field_settings.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/custom_fields.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/webhooks.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/projects.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/project_memberships.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/resources/workspaces.py -> build/bdist.macosx-10.10-x86_64/wheel/asana/resources
  copying build/lib/asana/session.py -> build/bdist.macosx-10.10-x86_64/wheel/asana
  copying build/lib/asana/__init__.py -> build/bdist.macosx-10.10-x86_64/wheel/asana
  running install_egg_info
  running egg_info
  writing requirements to asana.egg-info/requires.txt
  writing asana.egg-info/PKG-INFO
  writing top-level names to asana.egg-info/top_level.txt
  writing dependency_links to asana.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'asana.egg-info/SOURCES.txt'
  writing manifest file 'asana.egg-info/SOURCES.txt'
  Copying asana.egg-info to build/bdist.macosx-10.10-x86_64/wheel/asana-0.8.0-py2.7.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'

  ----------------------------------------
  Failed building wheel for asana
  Running setup.py clean for asana
  Failed to build asana
  ERROR: Failed to build one or more wheels¯

**Comment by solarmist** [comment]
It looks like the  itself is missing the LICENSE file.
And it's having the issue in the egg2dist function.

**Comment by solarmist** [comment]
Just need to add a MANIFEST.in file.

The following should be sufficient.
```
include LICENSE
include CONTRIBUTORS
include CHANGELOG
include README.md

```

**Comment by solarmist** [comment]
https://packaging.python.org/guides/distributing-packages-using-setuptools/?highlight=MANIFEST#manifest-in

**Comment by joetrollo** [comment]
Hi @solarmist, I'm not able to reproduce the issue, so I cannot confirm that the suggested fix is working. What command did you attempt that gave this error?

**Comment by joetrollo** [comment]
However, I can confirm that this change does include additional files in the final package, and is a safe addition, so I've made #82 to add it. It should be reviewed shortly.

**Comment by solarmist** [comment]
You can see the issue in https://pypi.org/project/asana/#files. The .whl file had the LICENSE file, but the .tar.gz didn't.

**Comment by solarmist** [comment]
Can you also publish a new version of the package to pypi?
