### ISSUE TITLE
BATCH API support in python-asana?

### ISSUE THREAD

**Issue by ameyalinge21** [Asana/python-asana#86]
Hello,

Can we use the Batch Api as mentioned in the below link to minimize the http requests?
https://asana.com/developers/documentation/getting-started/batch-api

**Comment by praecipula** [comment]
Hey @ameyalinge21,

You should be able to! At this point we don't have a resource for it in our Python client library, so there's nothing like `client.batch(params)`. However, our Python generated base classes are pretty "thin" wrappers around methods that delegate the request to `client` class mathods for each HTTP verb that actually makes the request. In this case, something like `client.post('/batch', params, **options)` (where `params` here is the JSON of the batch request) should work - see something like https://github.com/Asana/python-asana/blob/master/asana/resources/gen/tasks.py#L29 to see how our resources wrap a `post` request.
